# docker-compose.yml
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  postgres:
    image: postgres:16
    container_name: harry-postgres
    restart: always

    environment:
      POSTGRES_USER: harry
      POSTGRES_PASSWORD: potter
      POSTGRES_DB: hogwarts

    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  great_library_server:
    build: ./Great_Library_Server
    container_name: great-library-server
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    restart: always

  gryffindor_tower_server:
    build: ./Gryffindor_Tower_Server
    container_name: gryffindor-server

    ports:
      - "3002:3002" 
    depends_on:
      - postgres
    restart: always

  hagrid_hut_server:
    build: ./Hagrids_Hut_Server
    container_name: hagrid-hut-server
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    restart: always

  herbology_greenhouse_server:
    build: ./Herbology_Greenhouse_Server
    container_name: herbology-greenhouse-server
    ports:
      - "3004:3004"
    depends_on:
      - postgres
    restart: always


  muggle_world_server:
    build: ./Muggle_World_Server
    container_name: muggle-world-server
    ports:
      - "3005:3005"
    depends_on:
      - postgres
    restart: always

  platform_nine_quarters_server:
    build: ./Platform_Nine_Quarters_Server
    container_name: platform-nine-quarters-server
    ports:
      - "3006:3006"
    depends_on:
      - postgres
    restart: always

  quidditch_pitch_server:
    build: ./Quidditch_Pitch_Server
    container_name: quidditch-pitch-server
    ports:
      - "3007:3007"
    depends_on:
      - postgres
    restart: always

      
    


volumes:
  postgres_data:
