# docker-compose.yml
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  postgres:
    image: postgres:16
    container_name: harry-postgres
    restart: always

    environment:
      POSTGRES_USER: harry
      POSTGRES_PASSWORD: potter
      POSTGRES_DB: hogwarts

    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  gryffindor_tower_server:
    build: ./Gryffindor_Tower_Server
    container_name: gryffindor-server
    ports:
      - "3001:3009" 
    depends_on:
      - postgres
    restart: always

  great_library_server:
    build: ./Great_Libarary_Server
    container_name: great-library-server
    ports:
     - "3002:3010"
    depends_on:
      - postgres
    restart: always

  


  hagrids_hut_server:
    build: ./Hagrids_Hut_Server
    container_name: hagrids-hut-server
    ports:
      - 3003:3011
    depends_on:
      - postgres
    restart: always

  herbology_greenhouse_sever:
   
    build: ./Herbology_GreenHouse_Server
    container_name: herb-greenhouse-server
    ports:
      - "3004:3012"
    depends_on:
      - postgres
    restart: always

  hogwarts_library_server:
    build: ./Hogwarts_Library_Server
    container_name: hogwarts-lib-server
    ports:
      - "3005:3013"
    depends_on:
      - postgres
    restart: always

  muggle_world_server:
    build: ./Muggle_World_Server
    container_name: muggle-world-server
    ports:
      - "3006:3014"
    depends_on:
      - postgres
    restart: always
    
  platform_nine_quarters_server:
    build: ./Platform_Nine_Quarters_Server
    container_name: Platform-9-quaters-Server
    ports:
      - "3007:3015"
    depends_on:
      - postgres
    restart: always

  quidditch_pitch_server:
    build: ./Quidditch_Pitch_Server
    container_name: quidditch-pitch-server
    ports:
      - "3008:3016"
    depends_on:
      - postgres
    restart: always
      
    


volumes:
  postgres_data:
